// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RopeFinalProjectBackEnd.Contexts;

namespace RopeFinalProjectBackEnd.Migrations
{
    [DbContext(typeof(ReleaseTasksAPIContext))]
    [Migration("20200730142124_NewSeedData")]
    partial class NewSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RopeFinalProjectBackEnd.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Dakota",
                            Role = "Developer"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Bernard",
                            Role = "Developer"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Dan",
                            Role = "Developer"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Ron",
                            Role = "Developer"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Robert",
                            Role = "Release Manager"
                        });
                });

            modelBuilder.Entity("RopeFinalProjectBackEnd.Models.Priority", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Priorities");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Critical",
                            Value = 1
                        },
                        new
                        {
                            ID = 2,
                            Name = "High",
                            Value = 2
                        },
                        new
                        {
                            ID = 3,
                            Name = "Medium",
                            Value = 3
                        },
                        new
                        {
                            ID = 4,
                            Name = "Low",
                            Value = 4
                        });
                });

            modelBuilder.Entity("RopeFinalProjectBackEnd.Models.ReleaseTask", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssignedEmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CurrentDueTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentPriorityID")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStatusID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisisble")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ReleaseTasks");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AssignedEmployeeID = 1,
                            CreatedDate = new DateTime(2020, 7, 30, 10, 21, 24, 65, DateTimeKind.Local).AddTicks(5347),
                            CurrentDueTime = new DateTime(2020, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentPriorityID = 1,
                            CurrentStatusID = 1,
                            Description = "Validate Team Ready for Out of Service Page",
                            IsVisisble = true,
                            LastModifiedDate = new DateTime(2020, 7, 30, 10, 21, 24, 68, DateTimeKind.Local).AddTicks(272),
                            Name = "Validate Readiness"
                        },
                        new
                        {
                            ID = 2,
                            AssignedEmployeeID = 2,
                            CreatedDate = new DateTime(2020, 7, 30, 10, 21, 24, 68, DateTimeKind.Local).AddTicks(947),
                            CurrentDueTime = new DateTime(2020, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentPriorityID = 2,
                            CurrentStatusID = 2,
                            Description = "Update Message To Reflect Routine Maintenance",
                            IsVisisble = true,
                            LastModifiedDate = new DateTime(2020, 7, 30, 10, 21, 24, 68, DateTimeKind.Local).AddTicks(969),
                            Name = "Update User Message"
                        },
                        new
                        {
                            ID = 3,
                            AssignedEmployeeID = 3,
                            CreatedDate = new DateTime(2020, 7, 30, 10, 21, 24, 68, DateTimeKind.Local).AddTicks(994),
                            CurrentDueTime = new DateTime(2020, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentPriorityID = 3,
                            CurrentStatusID = 3,
                            Description = "Publish Content Updates/Changes, See Content Updates",
                            IsVisisble = true,
                            LastModifiedDate = new DateTime(2020, 7, 30, 10, 21, 24, 68, DateTimeKind.Local).AddTicks(999),
                            Name = "Push Content Changes"
                        },
                        new
                        {
                            ID = 4,
                            AssignedEmployeeID = 4,
                            CreatedDate = new DateTime(2020, 7, 30, 10, 21, 24, 68, DateTimeKind.Local).AddTicks(1007),
                            CurrentDueTime = new DateTime(2020, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentPriorityID = 4,
                            CurrentStatusID = 4,
                            Description = "Execute App Container Changes/Updates in Production, See App Container Tasks",
                            IsVisisble = true,
                            LastModifiedDate = new DateTime(2020, 7, 30, 10, 21, 24, 68, DateTimeKind.Local).AddTicks(1007),
                            Name = "Execute App Changes"
                        },
                        new
                        {
                            ID = 5,
                            AssignedEmployeeID = 2,
                            CreatedDate = new DateTime(2020, 7, 30, 10, 21, 24, 68, DateTimeKind.Local).AddTicks(1016),
                            CurrentDueTime = new DateTime(2020, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentPriorityID = 4,
                            CurrentStatusID = 2,
                            Description = "Deploy New U/I Layer Package, See U / I Layer Code",
                            IsVisisble = true,
                            LastModifiedDate = new DateTime(2020, 7, 30, 10, 21, 24, 68, DateTimeKind.Local).AddTicks(1020),
                            Name = "Deploy New UI"
                        },
                        new
                        {
                            ID = 6,
                            AssignedEmployeeID = 3,
                            CreatedDate = new DateTime(2020, 7, 30, 10, 21, 24, 68, DateTimeKind.Local).AddTicks(1029),
                            CurrentDueTime = new DateTime(2020, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentPriorityID = 4,
                            CurrentStatusID = 3,
                            Description = "Deploy Shared U/I Layer Package  See U / I Layer Code",
                            IsVisisble = true,
                            LastModifiedDate = new DateTime(2020, 7, 30, 10, 21, 24, 68, DateTimeKind.Local).AddTicks(1033),
                            Name = "Deploy Shared UI"
                        },
                        new
                        {
                            ID = 7,
                            AssignedEmployeeID = 1,
                            CreatedDate = new DateTime(2020, 7, 30, 10, 21, 24, 68, DateTimeKind.Local).AddTicks(1041),
                            CurrentDueTime = new DateTime(2020, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentPriorityID = 4,
                            CurrentStatusID = 1,
                            Description = "Deploy New Services Layer Package, See Services Layer Code",
                            IsVisisble = true,
                            LastModifiedDate = new DateTime(2020, 7, 30, 10, 21, 24, 68, DateTimeKind.Local).AddTicks(1041),
                            Name = "Deploy New Services"
                        },
                        new
                        {
                            ID = 8,
                            AssignedEmployeeID = 2,
                            CreatedDate = new DateTime(2020, 7, 30, 10, 21, 24, 68, DateTimeKind.Local).AddTicks(1050),
                            CurrentDueTime = new DateTime(2020, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentPriorityID = 2,
                            CurrentStatusID = 3,
                            Description = "Perform System Cache Refresh",
                            IsVisisble = true,
                            LastModifiedDate = new DateTime(2020, 7, 30, 10, 21, 24, 68, DateTimeKind.Local).AddTicks(1054),
                            Name = "Perform Refresh"
                        },
                        new
                        {
                            ID = 9,
                            AssignedEmployeeID = 2,
                            CreatedDate = new DateTime(2020, 7, 30, 10, 21, 24, 68, DateTimeKind.Local).AddTicks(1063),
                            CurrentDueTime = new DateTime(2020, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentPriorityID = 2,
                            CurrentStatusID = 2,
                            Description = "Bring Down Out of Service Page",
                            IsVisisble = true,
                            LastModifiedDate = new DateTime(2020, 7, 30, 10, 21, 24, 68, DateTimeKind.Local).AddTicks(1067),
                            Name = "Remove Service Page"
                        },
                        new
                        {
                            ID = 10,
                            AssignedEmployeeID = 4,
                            CreatedDate = new DateTime(2020, 7, 30, 10, 21, 24, 68, DateTimeKind.Local).AddTicks(1076),
                            CurrentDueTime = new DateTime(2020, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentPriorityID = 4,
                            CurrentStatusID = 3,
                            Description = "Update Message To Reflect Issues In The Event An Unplanned Outage Occurs",
                            IsVisisble = true,
                            LastModifiedDate = new DateTime(2020, 7, 30, 10, 21, 24, 68, DateTimeKind.Local).AddTicks(1076),
                            Name = "Update User Message"
                        },
                        new
                        {
                            ID = 11,
                            AssignedEmployeeID = 3,
                            CreatedDate = new DateTime(2020, 7, 30, 10, 21, 24, 68, DateTimeKind.Local).AddTicks(1084),
                            CurrentDueTime = new DateTime(2020, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentPriorityID = 3,
                            CurrentStatusID = 1,
                            Description = "Notify Group Validation Can Begin",
                            IsVisisble = true,
                            LastModifiedDate = new DateTime(2020, 7, 30, 10, 21, 24, 68, DateTimeKind.Local).AddTicks(1088),
                            Name = "Notify Validation Group"
                        },
                        new
                        {
                            ID = 12,
                            AssignedEmployeeID = 5,
                            CreatedDate = new DateTime(2020, 7, 30, 10, 21, 24, 68, DateTimeKind.Local).AddTicks(1097),
                            CurrentDueTime = new DateTime(2020, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentPriorityID = 3,
                            CurrentStatusID = 3,
                            Description = "System Monitoring Through Monday",
                            IsVisisble = true,
                            LastModifiedDate = new DateTime(2020, 7, 30, 10, 21, 24, 68, DateTimeKind.Local).AddTicks(1097),
                            Name = "Monitor System"
                        });
                });

            modelBuilder.Entity("RopeFinalProjectBackEnd.Models.Status", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "New",
                            Value = 1
                        },
                        new
                        {
                            ID = 2,
                            Name = "In Progress",
                            Value = 2
                        },
                        new
                        {
                            ID = 3,
                            Name = "Done",
                            Value = 3
                        },
                        new
                        {
                            ID = 4,
                            Name = "Cancelled",
                            Value = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
